norm = User.create(name: 'norm')
libby = User.create(name: 'libby')
brent = User.create(name: 'brent')
rachel = User.create(name: 'rachel')

norm.articles << Article.create(title: 'NPR and the Cisgender Critic Blues', body: "The publicity campaign for Transgender Dysphoria Blues, the latest album from Against Me!, has only begun and the last minute retractions and sensitivity edits are already underway! As it turns out, if we still can’t expect some people to wrap their heads around why phrases like “the gay lifestyle” are problematic, we probably shouldn’t hold our breath when it comes to their approach to transgender rock stars.
To be fair, a substantial number of contemporary music critics probably don’t know (or don’t think they know) a trans person, so their notion of what is or isn’t appropriate is largely guesswork. For these writers, then, there will be two major problems to contend with: First, they are going to need to critically evaluate a record whose subject matter is confusing and foreign to them. They will mediate Laura Jane Grace’s lyrics through their own assumptions about gender and sexuality, and more disconcertingly, through misconceptions they may have about trans people or the process of transitioning itself. The danger being, of course, that we’re about to be inundated with album reviews that more accurately reveal the gender anxieties of predominantly straight white cisgender men than they do any of Grace’s concerns.
The other problem these writers will grapple with is how to talk about Grace herself, and really, this shouldn’t be as hard: She’s a real person. She’s an artist. She is not available (nor is she making herself available) for objectification. The parameters and decorum with which we talk aboutany human being still apply.
This issue was put to the test over the weekend, when NPR posted an Against Me! album stream and writer Stephen Thompson was handily excoriated in the comments for writing that singer Laura Jane Grace “came out as preoperative transgender.” (This line has since been edited.) So where did he go wrong? For one, this particular phrasing puts an undue emphasis on “operative” status, as if gender identity depends on it. It doesn’t. But also, adjectives like these linguistically demonstrate our cultural obsession with trans bodies and presume that we have a right to know the personal physical details of these bodies in ways that we would never demand to know of anyone else. In her brilliant reprimand of Katie Couric, also over this weekend, Laverne Cox expands on this exact point:
The preoccupation with transition and surgery objectifies trans people. And then we don’t get to really deal with the real lived experiences. The reality of trans people’s lives is that so often we are targets of violence. We experience discrimination disproportionately to the rest of the community. Our unemployment rate is twice the national average; if you are a trans person of color, that rate is four times the national average. The homicide rate is highest among trans women. If we focus on transition, we don’t actually get to talk about those things.
A little bit of writerly advice, then: Surgery of any kind is personal, and an expression of entitlement to such detail is invasive at best. It’s as irrelevant to your critical work as asking whether or not Oasis are circumcised.
There are considerations and conventions that non-trans people need to learn. This is not negotiable. We need to know that language can be hostile to trans people, that language can prescribe and enforce the dominant heteronormative discourse, and that we—as cosigners on the social contract that is language—have every right to modify the way we speak about gender and transitioning in order to demarginalize those individuals whose realities are not served by their own tongue.
There is no shortage of trans etiquette work on the Internet, and this piece is not meant to replace that. I also don’t mean to speak on behalf of trans people, whose own voices are too often muted or ignored. If anything, consider this as more of a gentle proviso: Should you decide to write about Laura Jane Grace or any other trans person this year (or forever), you are hereby charged with a responsibility to keep from undermining their lives.
")
rachel.articles << Article.create(title: 'oh well', body: "The standard Lorem Ipsum passage, used since the 1500s
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
Section 1.10.32 of de Finibus Bonorum et Malorum, written by Cicero in 45 BC
Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
1914 translation by H. Rackham
But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?
Section 1.10.33 of de Finibus Bonorum et Malorum, written by Cicero in 45 BC
At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.
1914 translation by H. Rackham
On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains.")
norm.articles << Article.create(title: 'New Blog, New You', body: "Susan Sontag began a 1978 interview with Rolling Stone’s Jonathan Cott by pointing out the obvious. “Everything that happens to me is something I think about,” she told him. Thinking is one of the things I do.
In terms of gleaning insight into Sontag’s work, some might argue that this introduction is less a morsel than a pithy kernel. But for someone like me, someone who is always working towards some sort of self-definition that makes sense on an individual and collective level, I’d contend that she’s showing off: Sontag can explain her work so simply because she understands it well enough.
Over the last ten years, Nervous Acid has been a personal diary, an MP3 blog, a pop culture digest, and in its last incarnation, all of those things. But somewhere along the way, it also became a place for cultural criticism, political commentary, queer theory, and occasional notes from my academic fields of study, including but not limited to rhetoric, sociolinguistics, and education. Precisely how such seemingly divided interests should merge into one cohesive site is something that’s always nagged at me, and whether or not I’ve actually been successful in this endeavor has been difficult to shake out at best: If anything, my eclecticism had been less often a source of inspiration and more often the culprit for a lack of consistent output. Giving yourself the opportunity to write about anything, apparently, makes it much more likely to write nothing.
So this time last year, á propos of nothing in particular, I began (what I didn’t necessarily plan to be) a year-long sabbatical from Nervous Acid. In the interim, I realized that in order for this to work as a personally productive space, I needed to cast this project in a less amorphous shape. As much as we claim to love the freedom of choice, we only ever really need a couple of options.

On the first day of every semester, I tell my first-year university composition students that writing is a form of thinking. I tell them that grammar and technique is meaningless if you have nothing to say, that you can’t have anything to say if you’re not thinking hard enough, and that you’re not thinking hard enough if it doesn’t hurt at least a little bit. Growth hurts, I explain. That’s how you know it’s happening. Being a writer means you have chosen to bear the discomfort of being a writer.
That said, we also have the right to pick and choose our own battles.
Before the sabbatical, Nervous Acid became too much of a longform writing project—exhausting in itself, but also enervating enough to discourage writing outside of its immediate boundaries. This was the first thing I knew I had to fix: In order to dedicate more time and thought towards longform work—and, ideally, into books I want to write—this space needs to be a shortform outlet. A digital notebook with links to outside work that makes me think, along with commentary that expands on, challenges, or complicates that outside work. Sketches, perhaps, for something bigger.
The second thing I needed to fix was this site’s lack of self-definition. I stopped writing here because I didn’t know what to write about anymore, and in retrospect, that’s kind of crazy. To address the problem head-on, I have constructed a set of topical parameters to draw from, and I made sure that they reflected my interests today—not my interests from when I started the site, and not even necessarily those interests which have generated the largest amount of Tumblr interaction in recent history. Good writing (and good thinking) comes from being invested in your topic, and these are the topics I am currently invested in:
Rhetoric & Language I have a graduate degree in English with a specialization in Linguistics, so it’s quite possible that I am a little obsessed with the way that language works in identity formation, transmitting ideology, establishing and securing power relations, and enforcing hegemony through pop culture. Which might mean nothing to you now, but perhaps might mean something to you when I write about it later in layman’s terms.
Music & Literature In terms of cultural products that I spend a significant amount of time with, I have always turned to records and books as a way of helping me make sense of the world. Every now and then, I like to share my favorites and/or publicly articulate these connections in a way that maybe helps someone else.
Culture & Society Finally: There are categories that we use to organize society (ethnicity, gender, sexuality, class) and lenses we use to interpret culture (philosophy, religion, politics, science), but these constructs are only useful when the people that such tools are designed to describe and understand are not simply reduced to an abstraction. As an arguably functioning member of society, I believe I have an obligation to be a participant in this discussion—not merely an observer.

I understand that things around here will be different, and that perhaps some of the thousands of followers that I’ve amassed on Tumblr might want to take their attention elsewhere. I’m OK with that. Part of the process of coming back after a year is learning how to construct an online space on my own terms. After 10 years of blogging, it’s easy to get bogged down by outside critiques and an almost pathological need to publish clickbait. But I don’t need that anymore, if I ever did.
So welcome to the new Nervous Acid, where thinking is one of the things I do.")